#!/bin/bash

clear
cd ./BitCreekPeer/src/
make clean
cd ../..
rm -r BitCreekPeer2
cp -r BitCreekPeer BitCreekPeer2
cd ./BitCreekPeer/src/
make all
make prova &
cd ../../BitCreekPeer2/src/
make all 
make prova &
cd ../../BitCreekServer/src/
make clean
make all
make prova &
